import:
  - ~/.config/alacritty/theme.yml
  - ~/.config/alacritty/personal.yml

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 65
    lines: 20

  padding:
    x: 7
    y: 7

  # opacity: 0.95
  dynamic_padding: true
  dynamic_title: true
  gtk_theme_variant: dark

font:
  normal:
    family: JetBrainsMono Nerd Font
  bold:
    family: JetBrainsMono Nerd Font
  italic:
    family: JetBrainsMono Nerd Font
  bold_italic:
    family: JetBrainsMono Nerd Font
  size: 14.5
  offset:
    x: 1
    y: -1

cursor:
  style:
    shape: Block
    blinking: On

shell:
  program: /bin/fish

ipc_socket: true

colors:
  # Default colors
  primary:
    background: "#151515"
    foreground: "#E8E3E3"

  # Normal colors
  normal:
    black: "#151515"
    red: "#B66467"
    green: "#8C977D"
    yellow: "#D9BC8C"
    blue: "#8DA3B9"
    magenta: "#A988B0"
    cyan: "#8AA6A2"
    white: "#E8E3E3"

  # Bright colors
  bright:
    black: "#424242"
    red: "#B66467"
    green: "#8C977D"
    yellow: "#D9BC8C"
    blue: "#8DA3B9"
    magenta: "#A988B0"
    cyan: "#8AA6A2"
    white: "#E8E3E3"
