# # Colors (Horizon Dark)

# colors:
#   # Primary colors
#   primary:
#     background: '0x1c1e26'
#     foreground: '0xe0e0e0'
#   # Normal colors
#   normal:
#     black: '0x16161c'
#     red: '0xe95678'
#     green: '0x29d398'
#     yellow: '0xfab795'
#     blue: '0x26bbd9'
#     magenta: '0xee64ac'
#     cyan: '0x59e1e3'
#     white: '0xd5d8da'
#   # Bright colors
#   bright:
#     black: '0x5b5858'
#     red: '0xec6a88'
#     green: '0x3fdaa4'
#     yellow: '0xfbc3a7'
#     blue: '0x3fc4de'
#     magenta: '0xf075b5'
#     cyan: '0x6be4e6'
#     white: '0xd5d8da'


# Colors (One Dark)

colors:
  # Default colors
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'
  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'
  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'


# # Colors (Nord)

# colors:
#   # Default colors
#   primary:
#     background: '0x2E3440'
#     foreground: '0xD8DEE9'
#   # Normal colors
#   normal:
#     black:   '0x3B4252'
#     red:     '0xBF616A'
#     green:   '0xA3BE8C'
#     yellow:  '0xEBCB8B'
#     blue:    '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan:    '0x88C0D0'
#     white:   '0xE5E9F0'
#   # Bright colors
#   bright:
#     black:   '0x4C566A'
#     red:     '0xBF616A'
#     green:   '0xA3BE8C'
#     yellow:  '0xEBCB8B'
#     blue:    '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan:    '0x8FBCBB'
#     white:   '0xECEFF4'
