ipc_socket = true

[colors.bright]
black = "#424242"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.normal]
black = "#151515"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.primary]
background = "#151515"
foreground = "#E8E3E3"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.bold]
family = "JetBrainsMono NF"

[font.bold_italic]
family = "JetBrainsMono NF"

[font.italic]
family = "JetBrainsMono NF"

[font.normal]
family = "JetBrainsMono NF"

[font.offset]
x = 1
y = -1

[shell]
program = "/bin/fish"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 85
lines = 30

[window.padding]
x = 7
y = 7
