#!/bin/bash

CURRENT_DATE="$(date +'%Y-%m-%d-%s_grim.png')"
readonly output="$(xdg-user-dir PICTURES)/screenshots/$CURRENT_DATE"

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    if [ "$1" = "screen" ]; then
        grim "$output"
        wl-copy <"$output"
        if [ -v "$output" ]; then
            notify-send.sh -u critical "Something went wrong." "Can't take a screenshot."
        else
            notify-send.sh -d "$GUIFM $(dirname "$output")" -i "$output" "Screenshot has taken"
        fi
    elif [ "$1" = "custom" ]; then
        grim -g "$(slurp)" - | wl-copy
    fi
else
    true
fi
