#!/bin/bash

CURRENT_DATE="$(date +'%Y-%m-%d-%s.png')"
readonly output="$(xdg-user-dir PICTURES)/screenshots/$CURRENT_DATE"

if [ "$1" = "screen" ]; then
    tmpfile=$(mktemp)

    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        if grim - >"$tmpfile"; then
            mv "$tmpfile" "$output"
            wl-copy <"$output"
        else
            rm "$tmpfile"
        fi
    else
        if maim "$tmpfile.png"; then
            mv "$tmpfile.png" "$output"
            xclip -sel clip -t image/png "$output"
        else
            rm "$tmpfile.png"
        fi
    fi

    if [ -v "$output" ]; then
        notify-send.sh -u critical "Something went wrong." "Can't take a screenshot."
    else
        notify-send.sh -d "$GUIFM $(dirname "$output")" -i "$output" "Screenshot has taken"
    fi

elif [ "$1" = "custom" ]; then
    tmpfile=$(mktemp)

    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        if grim -g "$(slurp)" - >"$tmpfile"; then
            mv "$tmpfile" "$output"
            wl-copy <"$output"
        else
            rm "$tmpfile"
        fi
    else
        if maim -s "$tmpfile.png"; then
            mv "$tmpfile.png" "$output"
            xclip -sel clip -t image/png "$output"
        else
            rm "$tmpfile.png"
        fi
    fi

fi
