#!/usr/bin/env bash

# set X cursor to left pointer
xsetroot -cursor_name left_ptr

pgrep -x sxhkd >/dev/null || sxhkd &

$HOME/.config/polybar/launch.sh --docky &
pgrep -x cleanfullscreen >/dev/null || $HOME/.local/bin/cleanfullscreen &
pgrep -x nitrogen >/dev/null || nitrogen --restore &
pgrep -x agent >/dev/null || /usr/lib/geoclue-2.0/demos/agent &
pgrep -x redshift-gtk >/dev/null || redshift-gtk &
pgrep -x ulauncher >/dev/null || ulauncher --hide-window &
pgrep -x fcitx >/dev/null || fcitx &
pgrep -x flameshot >/dev/null || flameshot &
pgrep -x dunst >/dev/null || dunst &
pgrep -x picom >/dev/null || picom --experimental-backends -CGb &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 10

bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true

bspc config top_padding 40

# config examples
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Motrix state=floating
bspc rule -a Ulauncher border=off
bspc rule -a zoom state=floating
bspc rule -a Nitrogen state=floating
