#!/bin/sh

sudo su

sudo pacman --needed --noconfirm -Syu git base-devel rustup

exit

rustup default stable

git clone https://aur.archlinux.org/paru.git $HOME/paru
cd $HOME/paru
makepkg -si

paru --noconfirm --needed -S tmux \
    fish \
    dash \
    neovim \
    bat \
    fd \
    exa \
    fish \
    ripgrep \
    rcm
