#!/bin/sh

sudo true

sudo pacman --needed --noconfirm -Syu git base-devel rustup

rustup default stable

if ! command -v paru; then
    git clone https://aur.archlinux.org/paru.git "$HOME/paru"
    cd "$HOME/paru" || exit
    makepkg -si
fi

paru --noconfirm --needed -S tmux \
    fish \
    dash \
    neovim-git \
    nvim-packer-git \
    bat \
    fd \
    exa \
    fish \
    ripgrep \
    rcm
