#!/usr/bin/env fish

# cargo
set -U fish_user_paths $HOME/.cargo/bin $fish_user_paths

# local
set -U fish_user_paths $HOME/.local/bin $fish_user_paths

# npm
set -U fish_user_paths $HOME/.local/share/npm/bin $fish_user_paths

# go
set -U fish_user_paths $HOME/.local/share/go/bin $fish_user_paths
